---

- name: Apt | Add gitlab-ce key
  ansible.builtin.get_url:
    url: https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey
    dest: /etc/apt/keyrings/gitlab-ce.asc
    mode: '0644'
    force: true

- name: Apt | Add gitlab-ce repo
  ansible.builtin.deb822_repository:
    name: gitlab-ce
    install_python_debian: true
    types:
    - deb
    - deb-src
    uris: "https://packages.gitlab.com/gitlab/gitlab-ce/{{ ansible_facts[\"distribution\"] | lower }}/"
    suites: "{{ ansible_facts[\"distribution_release\"] | lower }}"
    components:
    - main
    signed_by: /etc/apt/keyrings/gitlab-ce.asc
    state: present

- name: Apt | Refresh cache after gitlab-ce repo change
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 0
  changed_when: false

- name: Apt | Set pin facts
  ansible.builtin.set_fact:
    _pin_package: gitlab-ce
    _pin_version: "{{ gitlab_release }}"
  when: gitlab_release is defined and gitlab_release != 'latest'

- name: Apt | Set gitlab-ce preferences file
  ansible.builtin.template:
    src: pin.pref.j2
    dest: "/etc/apt/preferences.d/gitlab-ce.pref"
    owner: root
    group: root
    mode: "0644"
  when: gitlab_release is defined and gitlab_release != 'latest'

- name: Apt | Install gitlab-ce
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: true
    autoremove: true
    update_cache: true
    cache_valid_time: 3600
  environment:
    DEBIAN_FRONTEND: noninteractive
  vars:
    packages:
    - gitlab-ce
  notify: Gitlab reconfigure

...
