---

- name: Add gitlab-ce key
  ansible.builtin.get_url:
    url: https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey
    dest: /etc/apt/trusted.gpg.d/gitlab-ce.asc
    mode: '0644'
    force: true

- name: Add gitlab-ce repo
  ansible.builtin.apt_repository:
    repo: "deb https://packages.gitlab.com/gitlab/gitlab-ce/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release | lower }} main"
    filename: gitlab-ce
    state: present
    update_cache: true

- name: Add gitlab-ce src-repo
  ansible.builtin.apt_repository:
    repo: "deb-src https://packages.gitlab.com/gitlab/gitlab-ce/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release | lower }} main"
    filename: gitlab-ce
    state: present
    update_cache: true

- name: Set pin facts
  ansible.builtin.set_fact:
    _pin_package: gitlab-ce
    _pin_version: "{{ gitlab_release }}"
  when: gitlab_release is defined and gitlab_release != 'latest'

- name: Set gitlab-ce preferences file
  ansible.builtin.template:
    src: pin.pref.j2
    dest: "/etc/apt/preferences.d/gitlab-ce.pref"
    owner: root
    group: root
    mode: 0644
  when: gitlab_release is defined and gitlab_release != 'latest'

- name: Install gitlab-ce
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: true
    autoremove: true
    update_cache: true
    cache_valid_time: 3600
  vars:
    packages:
      - gitlab-ce
  notify: Gitlab reconfigure

...
