---

- name: Apt | Add gitlab-ee key
  ansible.builtin.get_url:
    url: https://packages.gitlab.com/gitlab/gitlab-ee/gpgkey
    dest: /etc/apt/trusted.gpg.d/gitlab-ee.asc
    mode: '0644'
    force: true

- name: Apt | Add gitlab-ee repo
  ansible.builtin.apt_repository:
    repo: "deb https://packages.gitlab.com/gitlab/gitlab-ee/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release | lower }} main"
    filename: gitlab-ee
    state: present
    update_cache: true

- name: Apt | Add gitlab-ee src-repo
  ansible.builtin.apt_repository:
    repo: "deb-src https://packages.gitlab.com/gitlab/gitlab-ee/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release | lower }} main"
    filename: gitlab-ee
    state: present
    update_cache: true

- name: Apt | Set pin facts
  ansible.builtin.set_fact:
    _pin_package: gitlab-ee
    _pin_version: "{{ gitlab_release }}"
  when: gitlab_release is defined and gitlab_release != 'latest'

- name: Apt | Set gitlab-ee preferences file
  ansible.builtin.template:
    src: pin.pref.j2
    dest: "/etc/apt/preferences.d/gitlab-ee.pref"
    owner: root
    group: root
    mode: "0644"
  when: gitlab_release is defined and gitlab_release != 'latest'

- name: Apt | Install gitlab-ee
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: true
    autoremove: true
    update_cache: true
    cache_valid_time: 3600
  vars:
    packages:
      - gitlab-ee
  notify: Gitlab reconfigure

...
