---
- name: set https redirect to true
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: "^gitlab_rails\\['initial_root_password'\\] ="
    insertafter: "^# gitlab_rails\\['initial_root_password'\\] ="
    line: "gitlab_rails['initial_root_password'] = '{{ gitlab_initial_root_password }}'"
  notify: gitlab reconfigure
...
