---

- name: Fail when Password is shorter than 8 chars
  ansible.builtin.fail:
    msg: "The password needs to be at least 8 characters long"
  when: gitlab_initial_root_password|length < 8

- name: Check initial password file
  ansible.builtin.stat:
    path: /etc/gitlab/initial_root_password
  register: initial_root_password_file

- name: set initial root password
  ansible.builtin.lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: "^gitlab_rails\\['initial_root_password'\\] ="
    insertafter: "^# gitlab_rails\\['initial_root_password'\\] ="
    line: "gitlab_rails['initial_root_password'] = \"{{ gitlab_initial_root_password }}\""
  notify: Gitlab reconfigure
  when: not initial_root_password_file.stat.exists

...
