---
- name: Install dependencies packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: true
    autoremove: true
    update_cache: true
    cache_valid_time: 3600
  vars:
    packages:
    - curl
    - openssh-server
    - ca-certificates
    - tzdata
    - perl
    - gpg
    - expect

- name: Install gitlab-ce
  ansible.builtin.include_tasks: gitlab_ce.yml
  when: not gitlab_ee

- name: Install gitlab-ee
  ansible.builtin.include_tasks: gitlab_ee.yml
  when: gitlab_ee

- name: Configure gitlab.rb
  ansible.builtin.include_tasks: gitlab_config.yml
  loop: "{{ gitlab_config }}"

- name: Set initial root password
  ansible.builtin.include_tasks: initial_root_password.yml
  when: gitlab_initial_root_password is defined

- name: Setup mattermost
  ansible.builtin.include_tasks: mattermost.yml
  when: gitlab_mattermost_external_url is defined

- name: Flush the gitlab reconfigure handler
  ansible.builtin.meta: flush_handlers

# Pause for 60 seconds to let unicorn restart
- name: Wait for 60 seconds
  ansible.builtin.pause:
    seconds: 60

- name: Restart gitlab
  ansible.builtin.command: gitlab-ctl restart
  when: gitlab_run_reconfigure
  changed_when: false

...
