---
- name: add mattermost backup script
  template:
    src: mattermost-backup.sh.j2
    dest: /etc/mattermost-backup.sh
    owner: root
    group: root
    mode: 0700

- name: create mattermost backup dir
  file:
    path: "{{ gitlab_mattermost_backup_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0770

- name: enable mattermost
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: "^mattermost\\['enable'\\] ="
    insertafter: "^# mattermost\\['enable'\\] ="
    line: "mattermost['enable'] = true"
  notify: gitlab reconfigure

- name: set mattermost_external_url
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: 'mattermost_external_url '
    line: "mattermost_external_url '{{ gitlab_mattermost_external_url }}'"
  notify: gitlab reconfigure

- name: flush the gitlab reconfigure handler before manipulation the mattermost config
  meta: flush_handlers

- name: include mattermost_additional_configs.yml
  include: mattermost_additional_configs.yml

...
