---
- name: Read Mattermost JSON file
  command: cat /var/opt/gitlab/mattermost/config.json
  register: _mattermost_json

- name: alternate the mattermost json
  set_fact:
    mattermost_json: "{{ (_mattermost_json.stdout | from_json)|combine(gitlab_mattermost_additional_configs, recursive=True) }}"

- name: write back to object
  copy:
    content: "{{ mattermost_json | to_nice_json  }}"
    dest: /var/opt/gitlab/mattermost/config.json
    owner: mattermost
    group: root
    mode: 0644

...
