---

configs:
  memory: "16384"
  cpus: "8"
  # if a specific ansible version has to be used, this can be changed from latest to e.g. "2.11.0"
  ansible_version: "latest"
  role_name: "ansible-role-gitlab"
  ip: 192.168.56.54
  domain: gitlab.lokal
  aliases:
  - docker.lokal
  - chat.lokal
  - login.lokal

...
