---
- hosts: all
  become: true
  become_method: sudo

  vars:

    # gitlab_release: 12.4.3-ce.0
    gitlab_ee: True
    gitlab_initial_root_password: P@ssW0rd.123!
    gitlab_config:
    # set the URL
    - namespace: external_url
      value: "'http://gitlab.lokal'"
    # Enable the docker registry
    - namespace: registry_external_url
      value: "'http://docker.lokal'"
    - namespace: registry
      key: enable
      value: "true"
    # Set the mailpit catch all data
    - namespace: gitlab_rails
      key: gitlab_email_from
      value: "'gitlab@example.com'"
    - namespace: gitlab_rails
      key: gitlab_email_reply_to
      value: "'gitlab@example.com'"
    - namespace: gitlab_rails
      key: smtp_enable
      value: "true"
    - namespace: gitlab_rails
      key: smtp_address
      value: "'localhost'"
    - namespace: gitlab_rails
      key: smtp_port
      value: 1025
    # Enable backups to S3
    # - namespace: gitlab_rails
    #   key: backup_upload_connection
    #   block: |
    #     gitlab_rails['backup_upload_connection'] = {
    #       'provider' => 'AWS',
    #       'region' => 'eu-central-1',
    #       'aws_access_key_id' => 'XXXXXXX',
    #       'aws_secret_access_key' => 'XXXXXXX',
    #       # # If IAM profile use is enabled, remove aws_access_key_id and aws_secret_access_key
    #       'use_iam_profile' => false
    #     }
    # - namespace: gitlab_rails
    #   key: backup_upload_remote_directory
    #   value: "'__your_backup_upload_remote_directory__'"
    # Set the repositories data dir
    - regexp: "^# git_data_dirs"
      block: |
        git_data_dirs({
          "default" => {
            "path" => "/var/opt/gitlab/git-data"
          }
        })
    gitlab_mattermost_external_url: http://chat.lokal
    gitlab_mattermost_additional_configs:
      TeamSettings:
        SiteName: "chat.lokal"
      EmailSettings:
        EnableSignUpWithEmail: False
        EnableSignInWithEmail: False
        EnableSignInWithUsername: False
        SendEmailNotifications: True
        UseChannelInEmailNotifications: True
        FeedbackName: "chat.lokal"
        FeedbackEmail: "gitlab@example.com"
        SMTPUsername: "gitlab@example.com"
        SMTPServer: "localhost"
        SMTPPort: "1025"

  roles:
  - andrelohmann.root_colored_prompt
  - docker_compose_dependencies
  - ansible-role-gitlab

...
