---

roles:
- name: andrelohmann.root_colored_prompt
- name: andrelohmann.iptables
- name: andrelohmann.postgresql
- name: andrelohmann.terraform
- name: andrelohmann.golang
- name: andrelohmann.docker
- name: andrelohmann.gitlab_docker_runner

collections:
- name: community.postgresql
- name: community.docker
- name: community.general
- name: ansible.posix

...
