---

roles:
- andrelohmann.root_colored_prompt
- andrelohmann.postgresql
- andrelohmann.terraform
- andrelohmann.golang
- andrelohmann.docker
- andrelohmann.gitlab_docker_runner

collections:
- community.postgresql
- community.docker

...
