---

- name: Copy daemon.json.j2 to /etc/docker/daemon.json
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  register: _docker_daemon

- name: restart docker
  systemd:
    name: docker
    state: restarted
  when: _docker_daemon.changed

...
