---
version: '3.9'

services:
  postgresdb:
    image: postgres
    # image: postgres:15-alpine
    ports:
    - 5432:5432
    environment:
    - POSTGRES_DB=gitlab
    - POSTGRES_USER=gitlab
    - POSTGRES_PASSWORD=gitlab
    volumes:
    - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    volumes:
    - redisdata:/data
    ports:
    - 6379:6379
    command: redis-server --save 60 1 --loglevel warning --requirepass r3dis.S3cr3t
  redis-commander:
    # container_name: redis-commander
    # hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
    depends_on:
    - redis
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
    - 8888:80
    environment:
    - PGADMIN_DEFAULT_EMAIL=admin@example.com
    - PGADMIN_DEFAULT_PASSWORD=admin
    - PGADMIN_DISABLE_POSTFIX=True
    - PGADMIN_CONFIG_MAIL_SERVER="mailpit"
    - PGADMIN_CONFIG_MAIL_PORT=1025
    volumes:
    - pgadmindata:/var/lib/pgadmin
    depends_on:
    - postgresdb
    - mailpit
  mailpit:
    image: axllent/mailpit
    ports:
    - 8025:8025
    - 1025:1025
    environment:
    - POSTGRES_DB=apidemo
    - POSTGRES_USER=apidemo
    - POSTGRES_PASSWORD=apidemo
  kroki:
    image: yuzutech/kroki
    ports:
    - 8000:8000
  #elastic:
  #  image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
  #  ports:
  #  - 9200:9200

volumes:
  pgdata:
    name: "pgdata"
  pgadmindata:
    name: "pgadmindata"
  redisdata:
    name: "redisdata"
...
