---

- name: Add fail2ban gitlab configuration to jail.local
  ansible.builtin.blockinfile:
    path: /etc/fail2ban/jail.local
    marker: "# <!-- {mark} gitlab ANSIBLE MANAGED BLOCK -->"
    block: |
      [gitlab]
      enabled = true
      port = http,https
      filter = gitlab
      logpath = /var/log/gitlab/gitlab-rails/production_json.log
      maxretry = 3
      findtime = 2d
      bantime = 1h

- name: Add "beverage=lemon juice" outside a section in specified file
  community.general.ini_file:
    path: /etc/fail2ban/filter.d/gitlab.conf
    option: failregex
    value: '^{"method":"POST","path":"\/users\/sign_in",[a-zA-Z:,"]+,"status":0.*"remote_ip":"<HOST>",'
    state: present
    backup: yes

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

...
